// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Ernst.API.Blend.IntegratedTest.Feature
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class PBI55031TransformRequestFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "PBI55031.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "PBI55031TransformRequest", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "PBI55031TransformRequest")))
            {
                global::Ernst.API.Blend.IntegratedTest.Feature.PBI55031TransformRequestFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Status OK")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PBI55031TransformRequest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("200-Status-OK")]
        public virtual void StatusOK()
        {
            string[] tagsOfScenario = new string[] {
                    "200-Status-OK"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Status OK", null, new string[] {
                        "200-Status-OK"});
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
 testRunner.Given("User has Request File\'RequestFiles\\GetFeesForHomeLoanProductRequest.xml\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 6
 testRunner.And("User has Endpoint \'/quote/request\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 7
 testRunner.When("User Posted the file with contentType as \'application/xml\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 8
 testRunner.Then("Status code should be \'OK\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Invalid Endpoint")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PBI55031TransformRequest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("404-Notfound")]
        public virtual void InvalidEndpoint()
        {
            string[] tagsOfScenario = new string[] {
                    "404-Notfound"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Invalid Endpoint", null, new string[] {
                        "404-Notfound"});
#line 11
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 12
 testRunner.Given("User has Request File\'RequestFiles\\GetFeesForHomeLoanProductRequest.xml\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 13
 testRunner.And("User has Endpoint \'/request\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 14
 testRunner.When("User Posted the file with contentType as \'application/xml\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 15
 testRunner.Then("Status code should be \'NotFound\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Invalid Bearer Toekn")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PBI55031TransformRequest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("401-NotAuthorized")]
        public virtual void InvalidBearerToekn()
        {
            string[] tagsOfScenario = new string[] {
                    "401-NotAuthorized"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Invalid Bearer Toekn", null, new string[] {
                        "401-NotAuthorized"});
#line 18
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 19
 testRunner.Given("User has Request File\'RequestFiles\\GetFeesForHomeLoanProductRequest.xml\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 20
 testRunner.And("User has Endpoint \'/quote/request\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 21
 testRunner.When("User Posted the file without authorization and contentType as \'application/xml\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 22
 testRunner.Then("Status code should be \'Unauthorized\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Invalid Content")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PBI55031TransformRequest")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("400-BadRequest")]
        public virtual void InvalidContent()
        {
            string[] tagsOfScenario = new string[] {
                    "400-BadRequest"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Invalid Content", null, new string[] {
                        "400-BadRequest"});
#line 25
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 26
 testRunner.Given("User has Request File\'RequestFiles\\InvalidGetFeesForHomeLoanProductRequest.xml\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 27
 testRunner.And("User has Endpoint \'quote/request\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 28
 testRunner.When("User Posted the file with contentType as \'application/xml\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 29
 testRunner.Then("Status code should be \'BadRequest\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("With Purpose = \"Refinance\" but appraisedValue & purchasePrice having Value")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PBI55031TransformRequest")]
        public virtual void WithPurposeRefinanceButAppraisedValuePurchasePriceHavingValue()
        {
            string[] tagsOfScenario = ((string[])(null));
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("With Purpose = \"Refinance\" but appraisedValue & purchasePrice having Value", null, ((string[])(null)));
#line 31
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 32
testRunner.Given("User has Request File\'RequestFiles\\GetFeesForHomeLoanProductRequest.xml\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 33
testRunner.And("User has Endpoint \'quote/request\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Xpath",
                            "ValuetoModify"});
                table9.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/homeLoan/purpose",
                            "Refinance"});
                table9.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/propertyAddress/ci" +
                                "ty",
                            "WACity"});
                table9.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/propertyAddress/co" +
                                "unty",
                            "Adams County Census Area"});
                table9.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/propertyAddress/st" +
                                "ate",
                            "WA"});
                table9.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/appraisedValue",
                            "10000"});
                table9.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/purchasePrice",
                            "20000"});
                table9.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/homeLoan/loanAmount",
                            "300000"});
#line 34
testRunner.When("User has modified below  information in the  input file", ((string)(null)), table9, "When ");
#line hidden
#line 45
testRunner.When("User Posted the file with contentType as \'application/xml\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 46
testRunner.Then("Status code should be \'OK\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Xpath",
                            "Expectedvalue"});
                table10.AddRow(new string[] {
                            "/Request/ErnstRequest/TransactionCode",
                            "100"});
                table10.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/City",
                            "WACity"});
                table10.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/County",
                            "Adams"});
                table10.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/State",
                            "WA"});
                table10.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/EstimatedValue",
                            "0.0"});
                table10.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/MortgageAmount",
                            "300000"});
                table10.AddRow(new string[] {
                            "/Request/ErnstRequest/NumberOfPages/Deed",
                            "0"});
                table10.AddRow(new string[] {
                            "/Request/ErnstRequest/Deed/AmendmentModificationPages",
                            "0"});
                table10.AddRow(new string[] {
                            "/Request/ErnstRequest/Release/Pages",
                            "4"});
                table10.AddRow(new string[] {
                            "/Request/ErnstRequest/Release/NumberOfReleases",
                            "1"});
#line 47
testRunner.And("Verify Xml Response Values", ((string)(null)), table10, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("With Purpose other than \"Refinance\" and appraisedValue is greater than purchasePr" +
            "ice")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PBI55031TransformRequest")]
        public virtual void WithPurposeOtherThanRefinanceAndAppraisedValueIsGreaterThanPurchasePrice()
        {
            string[] tagsOfScenario = ((string[])(null));
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("With Purpose other than \"Refinance\" and appraisedValue is greater than purchasePr" +
                    "ice", null, ((string[])(null)));
#line 60
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 61
testRunner.Given("User has Request File\'RequestFiles\\GetFeesForHomeLoanProductRequest.xml\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 62
testRunner.And("User has Endpoint \'quote/request\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "Xpath",
                            "ValuetoModify"});
                table11.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/homeLoan/purpose",
                            "Purchase"});
                table11.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/propertyAddress/ci" +
                                "ty",
                            "WACity"});
                table11.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/propertyAddress/co" +
                                "unty",
                            "Adams County Census Area"});
                table11.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/propertyAddress/st" +
                                "ate",
                            "WA"});
                table11.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/appraisedValue",
                            "20000"});
                table11.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/purchasePrice",
                            "10000"});
                table11.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/homeLoan/loanAmount",
                            "300000"});
#line 63
testRunner.When("User has modified below  information in the  input file", ((string)(null)), table11, "When ");
#line hidden
#line 74
testRunner.When("User Posted the file with contentType as \'application/xml\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 75
testRunner.Then("Status code should be \'OK\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "Xpath",
                            "Expectedvalue"});
                table12.AddRow(new string[] {
                            "/Request/ErnstRequest/TransactionCode",
                            "100"});
                table12.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/City",
                            "WACity"});
                table12.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/County",
                            "Adams"});
                table12.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/State",
                            "WA"});
                table12.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/EstimatedValue",
                            "20000"});
                table12.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/MortgageAmount",
                            "300000"});
                table12.AddRow(new string[] {
                            "/Request/ErnstRequest/NumberOfPages/Mortgage",
                            "30"});
                table12.AddRow(new string[] {
                            "/Request/ErnstRequest/Mortgage/AmendmentModificationPages",
                            "0"});
                table12.AddRow(new string[] {
                            "/Request/ErnstRequest/NumberOfPages/Deed",
                            "3"});
                table12.AddRow(new string[] {
                            "/Request/ErnstRequest/Deed/AmendmentModificationPages",
                            "0"});
#line 76
testRunner.And("Verify Xml Response Values", ((string)(null)), table12, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("With Purpose other than \"Refinance\" and appraisedValue less than purchasePrice")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PBI55031TransformRequest")]
        public virtual void WithPurposeOtherThanRefinanceAndAppraisedValueLessThanPurchasePrice()
        {
            string[] tagsOfScenario = ((string[])(null));
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("With Purpose other than \"Refinance\" and appraisedValue less than purchasePrice", null, ((string[])(null)));
#line 90
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 91
testRunner.Given("User has Request File\'RequestFiles\\GetFeesForHomeLoanProductRequest.xml\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 92
testRunner.And("User has Endpoint \'quote/request\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "Xpath",
                            "ValuetoModify"});
                table13.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/homeLoan/purpose",
                            "Purchase"});
                table13.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/propertyAddress/ci" +
                                "ty",
                            "WACity"});
                table13.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/propertyAddress/co" +
                                "unty",
                            "Adams County Census Area"});
                table13.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/propertyAddress/st" +
                                "ate",
                            "WA"});
                table13.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/appraisedValue",
                            "10000"});
                table13.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/purchasePrice",
                            "20000"});
                table13.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/homeLoan/loanAmount",
                            "300000"});
#line 93
testRunner.When("User has modified below  information in the  input file", ((string)(null)), table13, "When ");
#line hidden
#line 103
testRunner.When("User Posted the file with contentType as \'application/xml\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 104
testRunner.Then("Status code should be \'OK\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "Xpath",
                            "Expectedvalue"});
                table14.AddRow(new string[] {
                            "/Request/ErnstRequest/TransactionCode",
                            "100"});
                table14.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/City",
                            "WACity"});
                table14.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/County",
                            "Adams"});
                table14.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/State",
                            "WA"});
                table14.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/EstimatedValue",
                            "20000"});
                table14.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/MortgageAmount",
                            "300000"});
                table14.AddRow(new string[] {
                            "/Request/ErnstRequest/NumberOfPages/Mortgage",
                            "30"});
                table14.AddRow(new string[] {
                            "/Request/ErnstRequest/Mortgage/AmendmentModificationPages",
                            "0"});
                table14.AddRow(new string[] {
                            "/Request/ErnstRequest/NumberOfPages/Deed",
                            "3"});
                table14.AddRow(new string[] {
                            "/Request/ErnstRequest/Deed/AmendmentModificationPages",
                            "0"});
#line 105
testRunner.And("Verify Xml Response Values", ((string)(null)), table14, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("With Purpose= \"MortgageModification\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PBI55031TransformRequest")]
        public virtual void WithPurposeMortgageModification()
        {
            string[] tagsOfScenario = ((string[])(null));
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("With Purpose= \"MortgageModification\"", null, ((string[])(null)));
#line 119
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 120
testRunner.Given("User has Request File\'RequestFiles\\GetFeesForHomeLoanProductRequest.xml\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 121
testRunner.And("User has Endpoint \'quote/request\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "Xpath",
                            "ValuetoModify"});
                table15.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/homeLoan/purpose",
                            "MortgageModification"});
                table15.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/propertyAddress/ci" +
                                "ty",
                            "WACity"});
                table15.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/propertyAddress/co" +
                                "unty",
                            "Adams Census Area"});
                table15.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/propertyAddress/st" +
                                "ate",
                            "WA"});
                table15.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/appraisedValue",
                            "10000"});
                table15.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/purchasePrice",
                            "20000"});
                table15.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/homeLoan/loanAmount",
                            "300000"});
#line 122
testRunner.When("User has modified below  information in the  input file", ((string)(null)), table15, "When ");
#line hidden
#line 132
testRunner.When("User Posted the file with contentType as \'application/xml\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 133
testRunner.Then("Status code should be \'OK\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "Xpath",
                            "Expectedvalue"});
                table16.AddRow(new string[] {
                            "/Request/ErnstRequest/TransactionCode",
                            "100"});
                table16.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/City",
                            "WACity"});
                table16.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/County",
                            "Adams"});
                table16.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/State",
                            "WA"});
                table16.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/EstimatedValue",
                            "20000"});
                table16.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/MortgageAmount",
                            "300000"});
                table16.AddRow(new string[] {
                            "/Request/ErnstRequest/NumberOfPages/Mortgage",
                            "0"});
                table16.AddRow(new string[] {
                            "/Request/ErnstRequest/Mortgage/AmendmentModificationPages",
                            "30"});
                table16.AddRow(new string[] {
                            "/Request/ErnstRequest/NumberOfPages/Deed",
                            "0"});
                table16.AddRow(new string[] {
                            "/Request/ErnstRequest/Deed/AmendmentModificationPages",
                            "3"});
#line 134
testRunner.And("Verify Xml Response Values", ((string)(null)), table16, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("With Purpose= \"Other/Unknown/Purchase\"")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PBI55031TransformRequest")]
        public virtual void WithPurposeOtherUnknownPurchase()
        {
            string[] tagsOfScenario = ((string[])(null));
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("With Purpose= \"Other/Unknown/Purchase\"", null, ((string[])(null)));
#line 147
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 148
testRunner.Given("User has Request File\'RequestFiles\\GetFeesForHomeLoanProductRequest.xml\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 149
testRunner.And("User has Endpoint \'quote/request\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "Xpath",
                            "ValuetoModify"});
                table17.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/homeLoan/purpose",
                            "Other"});
                table17.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/propertyAddress/ci" +
                                "ty",
                            "WACity"});
                table17.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/propertyAddress/co" +
                                "unty",
                            "Adams Borough"});
                table17.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/propertyAddress/st" +
                                "ate",
                            "WA"});
                table17.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/appraisedValue",
                            "10000"});
                table17.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/property/purchasePrice",
                            "20000"});
                table17.AddRow(new string[] {
                            "/GetFeesForHomeLoanProductRequest/homeLoanApplication/homeLoan/loanAmount",
                            "300000"});
#line 150
testRunner.When("User has modified below  information in the  input file", ((string)(null)), table17, "When ");
#line hidden
#line 160
testRunner.When("User Posted the file with contentType as \'application/xml\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 161
testRunner.Then("Status code should be \'OK\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "Xpath",
                            "Expectedvalue"});
                table18.AddRow(new string[] {
                            "/Request/ErnstRequest/TransactionCode",
                            "100"});
                table18.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/City",
                            "WACity"});
                table18.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/County",
                            "Adams"});
                table18.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/State",
                            "WA"});
                table18.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/EstimatedValue",
                            "20000"});
                table18.AddRow(new string[] {
                            "/Request/ErnstRequest/Property/MortgageAmount",
                            "300000"});
                table18.AddRow(new string[] {
                            "/Request/ErnstRequest/NumberOfPages/Mortgage",
                            "30"});
                table18.AddRow(new string[] {
                            "/Request/ErnstRequest/Mortgage/AmendmentModificationPages",
                            "0"});
                table18.AddRow(new string[] {
                            "/Request/ErnstRequest/NumberOfPages/Deed",
                            "3"});
                table18.AddRow(new string[] {
                            "/Request/ErnstRequest/Deed/AmendmentModificationPages",
                            "0"});
#line 162
testRunner.And("Verify Xml Response Values", ((string)(null)), table18, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
